spring.application.name: api-gateway
jwt.secretKey: jbhadbuehasndlewidjjedandnwledjiwjendlkanklenilopoqw
server.port: 8080
eureka.client.service-url.defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: Post-Services
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: User-Services
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: connections-service
          uri: lb://CONNECTION-SERVICE
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

