spring.application.name: api-gateway
jwt.secretKey: sjhbdfjsajfioasjefpoijwejfioajefjwesoprjpowy23u4irgbwebayiedgiuqwgwk
server.port: 8080
eureka.client.service-url.defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: Post-Services
          uri: lb://Post-Services
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: User-Services
          uri: lb://User-Services
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: connections-service
          uri: lb://connections-service
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

