spring.application.name=Post-Services

server.port=9010

spring.datasource.url=jdbc:postgresql://localhost:5432/Career_Link_App
spring.datasource.username=postgres
spring.datasource.password=avanish7080
spring.jpa.hibernate.ddl-auto=update